WOOLWORTH/Models/WOOLWORTHContext.cs
using MySql.Data.Entity;
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Linq;
using System.Web;

namespace WOOLWORTH.Models
{
    [DbConfigurationType(typeof(MySqlEFConfiguration))]

    public class WOOLWORTHContext : DbContext
    {
        // You can add custom code to this file. Changes will not be overwritten.
        // 
        // If you want Entity Framework to drop and regenerate your database
        // automatically whenever you change your model schema, please use data migrations.
        // For more information refer to the documentation:
        // http://msdn.microsoft.com/en-us/data/jj591621.aspx
    
        public WOOLWORTHContext() : base("name=WOOLWORTHContext")
        {
        }

        public System.Data.Entity.DbSet<WOOLWORTH.Models.WoolworthProducts> WoolworthProducts { get; set; }
    }
}

WOOLWORTH/Models/WoolworthProductCatergory.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace WOOLWORTH.Models
{
    public class WoolworthProductCatergory
    {
        [Key]
        public int catagoryID { get; set; }
        public string catagoryName { get; set; }
        public string catagoryDesc { get; set; }
    }
}

WOOLWORTH/Models/WoolworthProducts.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace WOOLWORTH.Models
{
    public class WoolworthProducts
    {
        [Key]
        public int productID { get; set; }
        public string productName { get; set; }
        public string productImage { get; set; }
        public double ProductPrice { get; set; }
        public double productDropPercent { get; set; }
        public string productDesc { get; set; }
        public DateTime productDateEndPromo { get; set; }
        public IEnumerable<WoolworthProductCatergory> productCatagories { get; set; }
    }
}

WOOLWORTH/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace WOOLWORTH.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult About()
        {
            ViewBag.Message = "Your application description page.";

            return View();
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "Your contact page.";

            return View();
        }
    }
}

WOOLWORTH/Controllers/WoolworthProductsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using WOOLWORTH.Models;

namespace WOOLWORTH.Controllers
{
    public class WoolworthProductsController : Controller
    {
        private WOOLWORTHContext db = new WOOLWORTHContext();

        // GET: WoolworthProducts
        public ActionResult Index()
        {
            return View(db.WoolworthProducts.ToList());
        }

        // GET: WoolworthProducts/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            WoolworthProducts woolworthProducts = db.WoolworthProducts.Find(id);
            if (woolworthProducts == null)
            {
                return HttpNotFound();
            }
            return View(woolworthProducts);
        }

        // GET: WoolworthProducts/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: WoolworthProducts/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "productID,productName,productImage,ProductPrice,productDropPercent,productDesc,productDateEndPromo")] WoolworthProducts woolworthProducts)
        {
            if (ModelState.IsValid)
            {
                db.WoolworthProducts.Add(woolworthProducts);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(woolworthProducts);
        }

        // GET: WoolworthProducts/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            WoolworthProducts woolworthProducts = db.WoolworthProducts.Find(id);
            if (woolworthProducts == null)
            {
                return HttpNotFound();
            }
            return View(woolworthProducts);
        }

        // POST: WoolworthProducts/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "productID,productName,productImage,ProductPrice,productDropPercent,productDesc,productDateEndPromo")] WoolworthProducts woolworthProducts)
        {
            if (ModelState.IsValid)
            {
                db.Entry(woolworthProducts).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(woolworthProducts);
        }

        // GET: WoolworthProducts/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            WoolworthProducts woolworthProducts = db.WoolworthProducts.Find(id);
            if (woolworthProducts == null)
            {
                return HttpNotFound();
            }
            return View(woolworthProducts);
        }

        // POST: WoolworthProducts/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            WoolworthProducts woolworthProducts = db.WoolworthProducts.Find(id);
            db.WoolworthProducts.Remove(woolworthProducts);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

WOOLWORTH/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body a href='#' background="~/img/slider3.jpg">

    @*<@*div class="container">
            <h4 style="font-family:'Lucida Sans', 'Lucida Sans Regular', 'Lucida Grande', 'Lucida Sans Unicode', Geneva, Verdana, sans-serif; color:aliceblue">
                <font color="black"><b>WELCOME!</b></font>
            </h4>
        </div>*@

    <div class="navbar navbar-inverse navbar-fixed-top" style="background-color:black">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>

                <img src="~/img/logo.jfif" />
                @*@Html.ActionLink("WOOLWORTHS", "Index", "WoolworthProducts", new { area = "" }, new { @class = "navbar-brand" })*@
            </div>
        </div>
    </div>
    <div class="container body-content">

        @RenderBody()

    </div>
    <hr />
    <footer style="background-color:black">

        <br />
        <br />
        <div class="container">
            <a href="#">
                <img src="~/img/logo.jfif"/>
            </a>
            <div class="row col-lg-12">

                <div class="col-lg-3">
                    <div style="text-emphasis-color:white">
                        <h4 href="#">
                            MY ACCOUNT
                        </h4>
                        <h4>
                            <a style="color:white" href="#">
                                Login/Register
                            </a>
                            <br />
                            <a style="color:white">
                                Orders
                            </a>
                            <br />
                            <a style="color:white">
                                Shopping Lists
                            </a>
                            <br />
                            <a style="color:white">
                                Acount Details
                            </a>
                            <br/>
                            <a style="color:white" href="#">
                                Link a Card
                            </a>
                            <br/>
                        
                        </h4>
                    </div>

                </div>
                <div class="col-lg-3">
                    <div style="text-emphasis-color:white">
                        <h4 href="#">
                            CUSTOMER SERVICE
                        </h4>
                        <h4>
                            <a style="color:white" href="#">
                                Help Centre
                            </a>
                            <br />
                            <a style="color:white">
                                Contact Us
                            </a>
                            <br />
                            <a style="color:white">
                                Usung Woolworths Online
                            </a>
                            <br />
                            <a style="color:white">
                                Delivery Options
                            </a>
                            <br/>
                            <a style="color:white" href="#">
                                Returns and Exchanges
                            </a>
                            <br />
                            <a style="color:white">
                                Terms and Conditions
                            </a>
                            <br />
                            <a style="color:white">
                                Corporate Sales
                            </a>
                            <br />
                        </h4>
                    </div>
                </div>
                    <div class="col-lg-3">
                        <div style="text-emphasis-color:white">
                            <h4 href="#">
                                ABOUT WOOLWORTHS
                            </h4>
                            <h4>
                                <a style="color:white" href="#">
                                    Store Locator
                                </a>
                                <br />
                                <a style="color:white">
                                    About Us
                                </a>
                                <br />
                                <a style="color:white">
                                    Careers
                                </a>
                                <br />
                                <a style="color:white">
                                    Press and News
                                </a>
                                <a style="color:white" href="#">
                                    Returns and Exchanges
                                </a>
                                <br />
                                <a style="color:white">
                                    Sustainability
                                </a>
                                <br />
                            </h4>
                        </div>

                    </div>
                    <div class="col-lg-3">
                        <div style="text-emphasis-color:white">
                            <h4 href="#">
                                FOLLOW US ON
                            </h4>
                            <h4>
                                <a style="color:white" href="#">
                                   Facebook
                                </a>
                                <br />
                                <a style="color:white">
                                    Twitter
                                </a>
                                <br />
                                <a style="color:white">
                                    Instagram
                                </a>
                                <br />
                                <a style="color:white">
                                    YouTube
                                </a>
                            </h4>
                        </div>
                    </div>
                </div>
                <p>&copy; @DateTime.Now.Year - Woolworths</p>
            </div>
    </footer>
    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>

WOOLWORTH/Views/WoolworthProducts/Create.cshtml
@model WOOLWORTH.Models.WoolworthProducts

@{
    ViewBag.Title = "Create";
}
<br/>




@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    <br/>
    
    <div class="form-horizontal" Style="background-color: black">
        <div>
            <h2  Style="color: white" ><b>Manager</b></h2>
            <h4 Style="color: white">WoolworthProducts</h4>
        </div>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group" Style="color: white">
            @Html.LabelFor(model => model.productName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.productName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.productName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group" Style="color: white">
            @Html.LabelFor(model => model.productImage, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.productImage, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.productImage, "", new { @class = "text-danger" })   


                <img id="image" alt="" width="280" height="280" />
                <input type="file"
                onchange="document.getElementById('image').src = window.URL.createObjectURL(this.files[0])">
            </div>
         
        </div>
        <div class="form-group" Style="color: white">
            @Html.LabelFor(model => model.ProductPrice, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ProductPrice, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ProductPrice, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group" Style="color: white">
            @Html.LabelFor(model => model.productDropPercent, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.productDropPercent, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.productDropPercent, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group" Style="color: white">
            @Html.LabelFor(model => model.productDesc, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.productDesc, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.productDesc, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group" Style="color: white">
            @Html.LabelFor(model => model.productDateEndPromo, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.productDateEndPromo, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.productDateEndPromo, "", new { @class = "text-danger" })
            </div>

        </div>
        <div class="form-group" Style="color: b">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
            <br />


        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

WOOLWORTH/Views/WoolworthProducts/Delete.cshtml
@model WOOLWORTH.Models.WoolworthProducts

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>WoolworthProducts</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.productName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.productName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.productImage)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.productImage)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.ProductPrice)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ProductPrice)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.productDropPercent)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.productDropPercent)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.productDesc)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.productDesc)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.productDateEndPromo)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.productDateEndPromo)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

WOOLWORTH/Views/WoolworthProducts/Details.cshtml
@model WOOLWORTH.Models.WoolworthProducts

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<div>
    <h4>WoolworthProducts</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.productName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.productName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.productImage)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.productImage)
        </dd>
        <dt> 
            @Html.DisplayNameFor(model => model.ProductPrice)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.ProductPrice)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.productDropPercent)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.productDropPercent)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.productDesc)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.productDesc)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.productDateEndPromo)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.productDateEndPromo)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.productID }) |
    @Html.ActionLink("Back to List", "Index")
</p>

WOOLWORTH/Views/WoolworthProducts/Edit.cshtml
@model WOOLWORTH.Models.WoolworthProducts

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
<div class="form-horizontal">
    <h4>WoolworthProducts</h4>
    <hr />
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
    @Html.HiddenFor(model => model.productID)

    <div class="form-group">
        @Html.LabelFor(model => model.productName, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.productName, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.productName, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.productImage, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.productImage, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.productImage, "", new { @class = "text-danger" })
        </div>
    </div>
    <div class="form-group">
        @Html.LabelFor(model => model.ProductPrice, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.ProductPrice, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.ProductPrice, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.productDropPercent, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.productDropPercent, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.productDropPercent, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.productDesc, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.productDesc, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.productDesc, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.productDateEndPromo, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.productDateEndPromo, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.productDateEndPromo, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <input type="submit" value="Save" class="btn btn-default" />
        </div>
    </div>
</div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

WOOLWORTH/Views/WoolworthProducts/Index.cshtml
@model IEnumerable<WOOLWORTH.Models.WoolworthProducts>

@{
    ViewBag.Title = "Index";
}

<br />

<!-- Page Content -->
<div class="container">
    <br />
    <div class="row">
        <div class="col-lg-3">
            <br />

            <table class="table table-striped " >
                <tr>
                    <th>
                        <a href="#" class="table-striped"Style="color: black">Men</a>
                    </th>
                    <th>
                        <a href="#" class="table-striped"Style="color: black">Women</a>
                    </th>
                    <th>
                        <a href="#" class="table-striped"Style="color: black">Kids</a>
                    </th>
                <tr />
            </table>
        </div>
    </div>
    <div id="myCarousel" class="carousel slide" data-ride="carousel">
        <!-- Indicators -->
        <ol class="carousel-indicators">
            <li data-target="#myCarousel" data-slide-to="0" class="active"></li>
            <li data-target="#myCarousel" data-slide-to="1"></li>
            <li data-target="#myCarousel" data-slide-to="2"></li>
        </ol>

        <!-- Wrapper for slides -->
        <div class="carousel-inner">
            <div class="item active">
                <a href='#'><img src="~/img/1st.jfif"></a>

            </div>

            <div class="item">

                <img src="~/img/2nd men.jfif" />
            </div>
        </div>
        <!-- Left and right controls -->
        <a class="left carousel-control" href="#myCarousel" data-slide="prev">
            <span class="glyphicon glyphicon-chevron-left"></span>
            <span class="sr-only">Previous</span>
        </a>
        <a class="right carousel-control" href="#myCarousel" data-slide="next">
            <span class="glyphicon glyphicon-chevron-right"></span>
            <span class="sr-only">Next</span>
        </a>
    </div>
    <div class="row">
        <div class="col-lg-12">
            <div class="row">
                @foreach (var item in Model)
    {
            <div class="col-lg-4 col-md-6 mb-4" style="padding:1% 1% 1% 1%;background-color:transparent">
                <div class="card h-100 list-group-item" style="padding: 5% 5% 5% 5%;background-color:transparent; border-radius:0%">
                    <a href="#">
                        <img class="card-img-top" src=@Url.Content(item.productImage) alt="Product Image" height="100%" width="100%" />
                    </a>
                    <div class="card-body" style="background-color:transparent">
                        <h4 class="card-title">
                            <a href="#" Style="color: white">@Html.DisplayFor(modelItem => item.productName)</a>
                        </h4>
                        <h4 Style="color: white">
                            R @Html.DisplayFor(modelItem  => item.ProductPrice)
                        </h4>
                        <p class="card-text"Style="color: white">
                            @Html.DisplayFor(modelItem => item.productDropPercent) % Off
                            <br />
                            @Html.DisplayFor(modelItem => item.productDesc)
                            <br />
                            @Html.DisplayFor(modelItem => item.productDateEndPromo)
                            <br />
                            @Html.DisplayFor(modelItem => item.productCatagories)
                        </p>
                    </div>
                    <div class="card-footer">
                        <small class="text-muted" style="color:white">&#9733; &#9733; &#9733; &#9733; &#9734;</small> 
                        @*@Html.ActionLink("Edit", "Edit", new { id = item.productID }) |
                        @Html.ActionLink("Details", "Details", new { id = item.productID }) |
                        @Html.ActionLink("Delete", "Delete", new { id = item.productID })*@
                    </div>

                </div>
            </div>

           

                }
            </div>
        </div>
    </div>
</div>
<!-- /.row -->
@*</div>*@
<!-- /.col-lg-9 -->
@*</div>*@
<!-- /.row -->
            </>
<!-- /.container -->
<!-- Footer -->
<footer class="py-5 bg-dark" >
    <div class="container"style="color:black">
        <p >@Html.ActionLink("MANAGER", "Create")</p>

    </div>
</footer>
<!-- /.container -->
@*@foreach (var item in Model)
    {
    }*@